name: Build and Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring app
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup JDK=17
        uses: actions/setup-java@v3
        with:
          distribution: 'alpine'
          java-version: 17

      - name: Grant Permissions
        run: chmod +x gradlew

      - name: Build app
        run: ./gradlew build
