name: Build and Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring app
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup JDK=17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Grant Permissions
        run: chmod +x gradlew

      - name: Build app
        run: ./gradlew build -x test

      - name: build Docker Image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/basic_reactive_demo:$(date-'%Y-%m-%d-%H-%S')

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/basic_reactive_demo:$(date-'%Y-%m-%d-%H-%S')